# Generated by Django 3.1.4 on 2021-04-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='hiya',
        ),
        migrations.AddField(
            model_name='employer',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to='avatar_pics'),
        ),
        migrations.AddField(
            model_name='employer',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employer',
            name='county',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employer',
            name='sector',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('interview', 'interview'), ('second round', 'second round')], max_length=15),
        ),
    ]
