# Generated by Django 3.1.4 on 2021-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('interview', 'interview'), ('rejected', 'rejected'), ('second round', 'second round')], max_length=15),
        ),
    ]
