# Generated by Django 3.1.4 on 2021-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210406_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='person_type',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('interview', 'interview'), ('second round', 'second round'), ('applied', 'applied'), ('rejected', 'rejected')], max_length=15),
        ),
    ]
