# Generated by Django 3.1.4 on 2021-04-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210402_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(default='Write your opitional cover letter here...', null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('interview', 'interview'), ('applied', 'applied'), ('second round', 'second round')], max_length=15),
        ),
    ]
