# Generated by Django 3.1.4 on 2021-04-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210412_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('interview', 'interview'), ('rejected', 'rejected'), ('second round', 'second round'), ('applied', 'applied')], max_length=15),
        ),
    ]
