# Generated by Django 3.1.4 on 2021-04-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210403_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('second round', 'second round'), ('applied', 'applied'), ('interview', 'interview'), ('rejected', 'rejected')], max_length=15),
        ),
    ]
