# Generated by Django 3.1.4 on 2021-04-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210406_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('interview', 'interview'), ('rejected', 'rejected'), ('second round', 'second round'), ('applied', 'applied')], max_length=15),
        ),
        migrations.CreateModel(
            name='MatchedSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.application')),
            ],
        ),
    ]
