# Generated by Django 3.1.4 on 2021-04-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210406_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='favourited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('second round', 'second round'), ('rejected', 'rejected'), ('interview', 'interview'), ('applied', 'applied')], max_length=15),
        ),
    ]
