# Generated by Django 3.1.4 on 2021-05-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210510_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('second round', 'second round'), ('interview', 'interview')], max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='description_personality',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
    ]
