# Generated by Django 3.1.4 on 2021-04-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210408_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='favourited',
            field=models.ManyToManyField(related_name='application', to='account.Employer'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('second round', 'second round'), ('interview', 'interview')], max_length=15),
        ),
    ]
