# Generated by Django 3.1.4 on 2021-05-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20210511_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='no_applicants',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('interview', 'interview'), ('applied', 'applied'), ('second round', 'second round'), ('rejected', 'rejected')], max_length=15),
        ),
    ]
