# Generated by Django 3.1.4 on 2021-05-12 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210512_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('interview', 'interview'), ('applied', 'applied'), ('second round', 'second round'), ('accepted', 'accepted')], max_length=15),
        ),
        migrations.CreateModel(
            name='JobRankings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.job')),
            ],
        ),
    ]
