# Generated by Django 3.1.4 on 2021-05-12 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210512_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrankings',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.employee'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('second round', 'second round'), ('interview', 'interview'), ('rejected', 'rejected'), ('applied', 'applied')], max_length=15),
        ),
    ]
