# Generated by Django 3.1.4 on 2021-05-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20210513_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('second round', 'second round'), ('accepted', 'accepted'), ('interview', 'interview'), ('applied', 'applied')], max_length=15),
        ),
        migrations.CreateModel(
            name='SharedThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('jobrank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.jobrankings')),
            ],
        ),
    ]
