# Generated by Django 3.1.4 on 2021-05-12 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20210513_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedthing',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.employee'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('interview', 'interview'), ('rejected', 'rejected'), ('second round', 'second round'), ('applied', 'applied'), ('accepted', 'accepted')], max_length=15),
        ),
    ]
