# Generated by Django 3.1.4 on 2021-04-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('second round', 'second round'), ('rejected', 'rejected'), ('interview', 'interview'), ('applied', 'applied')], max_length=15),
        ),
    ]
