# Generated by Django 3.1.4 on 2021-04-12 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210412_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversationmessages', to='account.employee'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversationmessages', to='account.employer'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('second round', 'second round'), ('interview', 'interview')], max_length=15),
        ),
    ]
