# Generated by Django 3.1.4 on 2021-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210503_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('second round', 'second round'), ('interview', 'interview'), ('rejected', 'rejected')], max_length=15),
        ),
    ]
