# Generated by Django 3.1.4 on 2021-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210503_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('interview', 'interview'), ('applied', 'applied'), ('rejected', 'rejected'), ('second round', 'second round')], max_length=15),
        ),
    ]
