# Generated by Django 3.1.4 on 2021-05-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20210512_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('second round', 'second round'), ('applied', 'applied'), ('accepted', 'accepted'), ('interview', 'interview')], max_length=15),
        ),
    ]
