# Generated by Django 3.1.4 on 2021-05-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210512_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('interview', 'interview'), ('second round', 'second round'), ('applied', 'applied'), ('rejected', 'rejected')], max_length=15),
        ),
    ]
