# Generated by Django 3.1.4 on 2021-05-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20210513_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedthing',
            name='jobrank',
        ),
        migrations.AddField(
            model_name='sharedthing',
            name='topthree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.topthree'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accepted', 'accepted'), ('second round', 'second round'), ('interview', 'interview'), ('applied', 'applied')], max_length=15),
        ),
    ]
