# Generated by Django 3.1.4 on 2021-05-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20210513_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedthing',
            name='topthree',
        ),
        migrations.AddField(
            model_name='sharedthing',
            name='jobrank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.jobrankings'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('interview', 'interview'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('applied', 'applied'), ('second round', 'second round')], max_length=15),
        ),
    ]
