# Generated by Django 3.1.4 on 2021-05-16 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20210513_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedthing',
            name='jobrank',
        ),
        migrations.AddField(
            model_name='sharedthing',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('applied', 'applied'), ('second round', 'second round'), ('interview', 'interview'), ('accepted', 'accepted')], max_length=15),
        ),
    ]
