# Generated by Django 3.1.4 on 2021-05-16 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20210516_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedthing',
            name='job',
        ),
        migrations.AddField(
            model_name='sharedthing',
            name='jobrank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.jobrankings'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('accepted', 'accepted'), ('second round', 'second round'), ('rejected', 'rejected'), ('interview', 'interview')], max_length=15),
        ),
    ]
