# Generated by Django 3.1.4 on 2021-05-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20210516_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='topthree',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('rejected', 'rejected'), ('accepted', 'accepted'), ('interview', 'interview'), ('second round', 'second round')], max_length=15),
        ),
    ]
