# Generated by Django 3.1.4 on 2021-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20210516_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrankings',
            name='topthree',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('interview', 'interview'), ('second round', 'second round'), ('rejected', 'rejected'), ('applied', 'applied')], max_length=15),
        ),
        migrations.DeleteModel(
            name='TopThree',
        ),
    ]
