# Generated by Django 3.1.4 on 2021-04-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='group',
            field=models.CharField(choices=[('sj', 'sj'), ('sp', 'sp'), ('nt', 'nt'), ('nf', 'nf')], max_length=200, null=True),
        ),
    ]
