# Generated by Django 3.1.4 on 2021-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='group',
            field=models.CharField(choices=[('nf', 'nf'), ('nt', 'nt'), ('sp', 'sp'), ('sj', 'sj')], max_length=200, null=True),
        ),
    ]
