# Generated by Django 3.1.4 on 2021-04-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_auto_20210406_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='group',
            field=models.CharField(choices=[('sj', 'sj'), ('sp', 'sp'), ('nf', 'nf'), ('nt', 'nt')], max_length=200, null=True),
        ),
    ]
