# Generated by Django 3.1.4 on 2021-04-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0002_auto_20210402_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='group',
            field=models.CharField(choices=[('sp', 'sp'), ('sj', 'sj'), ('nt', 'nt'), ('nf', 'nf')], max_length=200, null=True),
        ),
    ]
