# Generated by Django 3.1.4 on 2021-04-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0003_auto_20210403_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='group',
            field=models.CharField(choices=[('sj', 'sj'), ('nf', 'nf'), ('nt', 'nt'), ('sp', 'sp')], max_length=200, null=True),
        ),
    ]
