# Generated by Django 3.1.4 on 2021-04-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personality', '0003_auto_20210406_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='group',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
