# Generated by Django 3.1.4 on 2021-05-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210503_1416'),
        ('personality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personality',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.employee'),
        ),
    ]
